-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.products
(
    product_id smallserial,
    name character varying(10),
    price money,
    PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    user_id smallserial,
    name character varying(15),
    PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.cart
(
    product_id smallint,
    qty integer,
    PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS public.order_header
(
    order_id smallserial,
    user_id smallint,
    order_date timestamp without time zone,
    PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS public.order_details
(
    order_header smallint,
    product_id smallint,
    qty smallint
);
END;